name: MelonedApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
      - name: Build APK
        run: flutter build apk --build-name=1.9-Beta7 --build-number=1
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk 
          path: build/app/outputs/flutter-apk/app-release.apk
