- name: Flutter action
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@1e6ee87cb840500837bcd50a667fb28815d8e310
  uses: subosito/flutter-action@v2.7.1
  with:
    # The Flutter version to make available on the path
    flutter-version: # optional, default is any
    # The Flutter build release channel
    channel: # optional, default is stable
    # Cache the Flutter SDK
    cache: # optional
    # Identifier for the Flutter SDK cache
    cache-key: # optional, default is flutter-:os:-:channel:-:version:-:arch:-:hash:
    # Flutter SDK cache path
    cache-path: # optional, default is ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
    # The architecture of Flutter SDK executable (x64 or arm64)
    architecture: # optional, default is ${{ runner.arch }}
  steps:
- uses: actions/checkout@v3
- uses: actions/setup-java@v2
  with:
    distribution: 'zulu'
    java-version: '11'
- uses: subosito/flutter-action@v2
  with:
    flutter-version: '3.0.5'
- run: flutter pub get
- run: flutter test
- run: flutter build apk
- run: flutter build appbundle
